services:
  - type: web
    name: employee-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: mysql-106cb38a-dikesanket15-3518.c.aivencloud.com
      - key: DB_PORT
        value: "21511"
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_SSL
        value: "true"
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PASSWORD
        sync: false
      - key: ADMIN_NAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLIENT_URL
        value: http://localhost:5173